language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_install:
  - npm install npm --global
before_script:
  - node script/create-test-tables.js pg://postgres@127.0.0.1:5432/postgres
env:
  - PGUSER=postgres PGDATABASE=postgres
